### ISSUE TITLE
DEBUG?

### ISSUE THREAD

**Issue by dobrynski** [dale3h/hassctl#5]
First of all, I absolutely LOVE hassctl and it has made my life much easier. Thank you!

Now I have recently had a need to make use of debug.. And while hassctl supports log and error.. no debug! Any chance you could add DEBUG? I would assume that much like log encompasses everything below it like DEBUG and ERROR, debug would encompass DEBUG and ERROR.

Does that sound like a reasonable idea?

Oh.. and bakcup? I recently had a massive scare with HA going nuts.. Still don't know if it's kosher.. A decent and easy to automate backup would take a load of my shoulders.

Regards,
Michal (aka mihalski)

**Comment by dale3h** [comment]
These are both great ideas. I already have plans to implement a backup command, but I will also work on getting a debug command implemented as well.

Thank you for your feedback!

**Comment by dale3h** [comment]
`hassctl debug` feature has been added, but its output is restricted to just "debug" messages.
